[package]
name = "fk-app"
description = "Application builder and main loop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["gamedev", "game-engine", "winit", "window", "input"]
categories = ["game-engines", "gui"]

[dependencies]
fk-math.workspace = true
fk-geometry.workspace = true
bevy_ecs.workspace = true
winit.workspace = true
raw-window-handle.workspace = true
softbuffer.workspace = true
serde.workspace = true
toml.workspace = true
directories.workspace = true
tracing.workspace = true

[dev-dependencies]
fk-geometry-euclidean.workspace = true

[lints]
workspace = true
