[package]
name = "fk-assets"
description = "Mesh loading, embedding into curved spaces, geodesic refinement"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["gltf", "mesh", "assets", "gamedev", "geodesic"]
categories = ["game-development", "graphics"]

[dependencies]
fk-math.workspace = true
fk-geometry.workspace = true
fk-quotient.workspace = true
fk-render.workspace = true
gltf.workspace = true

[dev-dependencies]
fk-geometry-euclidean.workspace = true
fk-geometry-hyperbolic.workspace = true
fk-geometry-spherical.workspace = true

[lints]
workspace = true
