//! Quotient spaces: a geometry divided by a discrete group of isometries (its deck group), with
//! a fundamental domain, the faces that bound it and what crossing one does to a pose.
//!
//! A [`Quotient`] is a geometry `G`, a centre point `c` and the generators of the deck group.
//! Its fundamental domain is the Dirichlet domain about `c`: the points nearer `c` than any of
//! the translates `γ(c)` of `c` by a generator or a generator's inverse. It is defined by the
//! metric alone, so it is the same code in every geometry; in E³ with three orthogonal
//! translations it is the box of a flat torus ([`Quotient::from_translations`]).
//!
//! - Each generator and each inverse is a face: the bisector between `c` and `γ(c)`, named by
//!   its [`Letter`]. [`Quotient::which_face`] says which face a point is beyond, if any.
//! - Crossing a face (`γ(c)` nearer than `c`) brings a pose back into the domain by `γ⁻¹`,
//!   `pose ← γ⁻¹ ∘ pose`, and appends the face's letter to the pose's [`ChartTag`]: the copy of
//!   the domain it is really in is `word ∘ pose` ([`Quotient::cross`], [`Quotient::reduce`]).
//! - [`Quotient::translates`] lists the group's elements up to a word length, breadth first,
//!   each once (compared by where they take the centre): the copies of the domain a renderer
//!   draws within its horizon, the ghosts a collider tests.
//! - [`Quotient::shortest`] is the distance between two points of the quotient: the least
//!   over the translates of one of them.
//!
//! Words compose left to right: the letters of a word `w = l₁ l₂ … lₙ` stand for
//! `γ(l₁) ∘ γ(l₂) ∘ … ∘ γ(lₙ)`.

use fk_geometry::{Geometry, GroupElement};
use fk_math::Real;
pub use fk_scene::{ChartTag, Letter};

/// Two translates of the centre nearer than this are the same element.
const SAME: Real = 1e-7;

/// Most faces crossed by one [`Quotient::reduce`] before it gives up: the pose was further
/// out than any sensible step.
const MOST_CROSSINGS: usize = 64;

/// A geometry divided by a discrete group of isometries: see the [crate docs](crate).
pub struct Quotient<G: Geometry> {
    centre: G::Point,
    generators: Vec<G::Isometry>,
    inverses: Vec<G::Isometry>,
}

impl<G: Geometry> Clone for Quotient<G> {
    fn clone(&self) -> Self {
        Self {
            centre: self.centre,
            generators: self.generators.clone(),
            inverses: self.inverses.clone(),
        }
    }
}

impl<G: Geometry> std::fmt::Debug for Quotient<G> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Quotient")
            .field("centre", &self.centre)
            .field("generators", &self.generators)
            .finish()
    }
}

/// An element of the deck group: its word and the isometry it stands for.
#[derive(Clone, Debug, PartialEq)]
pub struct Translate<I> {
    /// The word, freely reduced.
    pub word: ChartTag,
    /// `γ(word)`.
    pub isometry: I,
}

impl<G: Geometry> Quotient<G> {
    /// `G` divided by the group generated by `generators`, its fundamental domain the
    /// Dirichlet domain about `centre`.
    ///
    /// # Panics
    ///
    /// If there are more generators than a [`Letter`] can name.
    pub fn new(centre: G::Point, generators: Vec<G::Isometry>) -> Self {
        assert!(
            u16::try_from(generators.len()).is_ok(),
            "too many generators"
        );
        let inverses = generators.iter().map(GroupElement::inverse).collect();
        Self {
            centre,
            generators,
            inverses,
        }
    }

    /// `G` divided by the translations `exp(transvection(v))` for each `v`, about `centre`:
    /// with three orthogonal ones in E³, a flat torus.
    pub fn from_translations(centre: G::Point, translations: &[G::Tangent]) -> Self {
        let generators = translations
            .iter()
            .map(|v| G::Isometry::exp(&G::transvection(v)))
            .collect();
        Self::new(centre, generators)
    }

    /// The lens space `L(p, q)` when `G` is the 3-sphere: the quotient by the group of order
    /// `p` generated by the screw motion along the great circle through the origin in the
    /// reference direction 2 (the eye's backwards), `2π/p` along it while turning `2πq/p` in
    /// the plane of directions 0 and 1. For `q` prime to `p` it is a manifold; its fundamental
    /// domain about the origin is a lens between two caps. (In other geometries the same screw
    /// generates a lattice of copies along the axis: in E³, a twisted cylinder.)
    pub fn lens(p: u32, q: u32) -> Self {
        let step = std::f64::consts::TAU / Real::from(p);
        let along = G::Isometry::exp(&G::transvection(&(G::origin_frame(2) * step)));
        let turn = G::Isometry::exp(
            &(G::rotation(&G::origin_frame(0), &G::origin_frame(1)) * (step * Real::from(q))),
        );
        Self::new(G::origin(), vec![along.compose(&turn)])
    }

    /// The centre of the fundamental domain.
    pub fn centre(&self) -> &G::Point {
        &self.centre
    }

    /// The generators.
    pub fn generators(&self) -> &[G::Isometry] {
        &self.generators
    }

    /// The isometry a letter stands for: its generator, or that generator's inverse.
    ///
    /// # Panics
    ///
    /// If the letter names no generator of this quotient.
    pub fn element(&self, letter: Letter) -> G::Isometry {
        let i = usize::from(letter.generator);
        if letter.inverse {
            self.inverses[i]
        } else {
            self.generators[i]
        }
    }

    /// The isometry a word stands for.
    pub fn word(&self, word: &ChartTag) -> G::Isometry {
        word.letters()
            .iter()
            .fold(G::Isometry::identity(), |sum, &letter| {
                sum.compose(&self.element(letter))
            })
    }

    /// Every face: each generator's letter and its inverse's.
    pub fn faces(&self) -> impl Iterator<Item = Letter> + '_ {
        (0..self.generators.len()).flat_map(|i| {
            let letter = Letter::new(i as u16);
            [letter, letter.inverse()]
        })
    }

    /// How far beyond face `face` the point `p` is: `d(p, c) − d(p, γ(c))`, positive beyond it
    /// (nearer the translate than the centre), negative inside.
    pub fn beyond(&self, p: &G::Point, face: Letter) -> Real {
        let translate = G::apply(&self.element(face), &self.centre);
        G::distance(p, &self.centre) - G::distance(p, &translate)
    }

    /// The face `p` is furthest beyond, if it is beyond any: outside the fundamental domain.
    pub fn which_face(&self, p: &G::Point) -> Option<Letter> {
        self.faces()
            .map(|face| (face, self.beyond(p, face)))
            .filter(|(_, beyond)| *beyond > 0.0)
            .max_by(|a, b| a.1.total_cmp(&b.1))
            .map(|(face, _)| face)
    }

    /// If the pose's point (where it takes the origin) is beyond a face, brings it back across
    /// that face, `pose ← γ⁻¹ ∘ pose`, appends the face's letter to `chart` and returns the
    /// face.
    pub fn cross(&self, pose: &mut G::Isometry, chart: &mut ChartTag) -> Option<Letter> {
        let face = self.which_face(&G::apply(pose, &G::origin()))?;
        *pose = self.element(face.inverse()).compose(pose);
        pose.renormalize();
        chart.push(face);
        Some(face)
    }

    /// Crosses faces until the pose is in the fundamental domain; the faces crossed, in order.
    /// Gives up after a few dozen.
    pub fn reduce(&self, pose: &mut G::Isometry, chart: &mut ChartTag) -> Vec<Letter> {
        let mut crossed = Vec::new();
        while crossed.len() < MOST_CROSSINGS {
            match self.cross(pose, chart) {
                Some(face) => crossed.push(face),
                None => break,
            }
        }
        crossed
    }

    /// The group's elements whose words have at most `length` letters, the identity first,
    /// then breadth first; each element once, compared by where it takes the centre.
    pub fn translates(&self, length: usize) -> Vec<Translate<G::Isometry>> {
        let mut found = vec![Translate {
            word: ChartTag::identity(),
            isometry: G::Isometry::identity(),
        }];
        let mut points = vec![self.centre];
        let mut frontier = 0..1;
        for _ in 0..length {
            let start = found.len();
            for i in frontier.clone() {
                for face in self.faces().collect::<Vec<_>>() {
                    let isometry = found[i].isometry.compose(&self.element(face));
                    let point = G::apply(&isometry, &self.centre);
                    if points.iter().any(|seen| G::distance(seen, &point) < SAME) {
                        continue;
                    }
                    let mut word = found[i].word.clone();
                    word.push(face);
                    points.push(point);
                    found.push(Translate { word, isometry });
                }
            }
            frontier = start..found.len();
        }
        found
    }

    /// The distance from `a` to `b` in the quotient, through the translates of `b` with words
    /// of at most `length` letters, and the translate that gives it.
    pub fn shortest(
        &self,
        a: &G::Point,
        b: &G::Point,
        length: usize,
    ) -> (Real, Translate<G::Isometry>) {
        self.translates(length)
            .into_iter()
            .map(|translate| (G::distance(a, &G::apply(&translate.isometry, b)), translate))
            .min_by(|x, y| x.0.total_cmp(&y.0))
            .expect("the identity is always a translate")
    }
}

#[cfg(test)]
mod tests {
    use fk_geometry_euclidean::{E3, Se3};
    use fk_math::nalgebra::{Point3, UnitQuaternion, Vector3};

    use super::*;

    const L: Real = 10.0;

    fn torus() -> Quotient<E3> {
        Quotient::from_translations(
            Point3::origin(),
            &[Vector3::x() * L, Vector3::y() * L, Vector3::z() * L],
        )
    }

    fn at(x: Real, y: Real, z: Real) -> Se3 {
        Se3::exp(&E3::transvection(&Vector3::new(x, y, z)))
    }

    #[test]
    fn the_torus_domain_is_its_box() {
        let q = torus();
        assert_eq!(q.which_face(&Point3::new(4.9, -4.9, 0.0)), None);
        let beyond = q.which_face(&Point3::new(5.1, 0.0, 0.0)).unwrap();
        assert_eq!(beyond, Letter::new(0));
        let behind = q.which_face(&Point3::new(0.0, 0.0, -5.2)).unwrap();
        assert_eq!(behind, Letter::new(2).inverse());
    }

    #[test]
    fn exiting_and_reentering_gives_an_equivalent_pose() {
        let q = torus();
        let turn = UnitQuaternion::from_euler_angles(0.3, -0.2, 1.1);
        let mut pose = at(4.0, 1.0, -2.0);
        pose.rotation = turn;
        let start = pose;
        let mut chart = ChartTag::identity();
        // Walks out through +x, a whole turn round the torus in steps.
        let step = at(0.7, 0.0, 0.0);
        for _ in 0..15 {
            pose = step.compose(&pose);
            q.reduce(&mut pose, &mut chart);
            assert!(
                q.which_face(&pose.translation.into()).is_none(),
                "in the box"
            );
        }
        // 10.5 m along x: back near the start, half a metre on, and one turn round.
        let moved = pose.translation - start.translation;
        assert!(
            (moved - Vector3::new(0.5, 0.0, 0.0)).norm() < 1e-9,
            "{moved}"
        );
        assert!(pose.rotation.angle_to(&turn) < 1e-12);
        assert_eq!(chart.letters(), &[Letter::new(0)]);
        // The word puts it back where it really is.
        let real = q.word(&chart).compose(&pose);
        let walked = Vector3::new(4.0 + 10.5, 1.0, -2.0);
        assert!((real.translation - walked).norm() < 1e-9);
    }

    #[test]
    fn the_torus_relations_are_the_identity() {
        let q = torus();
        for (i, j) in [(0, 1), (1, 2), (0, 2)] {
            let (a, b) = (Letter::new(i), Letter::new(j));
            // a b a⁻¹ b⁻¹: the generators commute.
            let word = ChartTag::from_letters([a, b, a.inverse(), b.inverse()]);
            let g = q.word(&word);
            let p = Point3::new(1.0, 2.0, 3.0);
            assert!((E3::apply(&g, &p) - p).norm() < 1e-12);
        }
    }

    #[test]
    fn translates_are_each_listed_once_breadth_first() {
        let q = torus();
        let one = q.translates(1);
        assert_eq!(one.len(), 7, "the identity and the six faces");
        assert!(one[0].word.is_identity());
        // Words of up to two letters on three commuting generators: the points of the
        // lattice at most two steps from the centre, 1 + 6 + 18.
        assert_eq!(q.translates(2).len(), 25);
    }

    #[test]
    fn the_shortest_way_goes_round() {
        let q = torus();
        let (d, translate) =
            q.shortest(&Point3::new(-4.5, 0.0, 0.0), &Point3::new(4.5, 0.0, 0.0), 1);
        assert!((d - 1.0).abs() < 1e-12, "{d}");
        assert_eq!(translate.word.letters(), &[Letter::new(0).inverse()]);
    }

    #[test]
    fn a_road_wraps_forward_only_when_asked() {
        // One translation 120 m along −z, the domain centred 60 m out: a road whose way on is
        // endless.
        let q = Quotient::<E3>::from_translations(
            Point3::new(0.0, 0.0, -60.0),
            &[-Vector3::z() * 120.0],
        );
        let ahead = q.which_face(&Point3::new(0.0, 0.0, -121.0));
        assert_eq!(ahead, Some(Letter::new(0)));
        let behind = q.which_face(&Point3::new(0.0, 0.0, 1.0));
        assert_eq!(behind, Some(Letter::new(0).inverse()));
        let mut pose = at(0.0, 0.0, -121.0);
        let mut chart = ChartTag::identity();
        q.cross(&mut pose, &mut chart);
        assert!((pose.translation.z + 1.0).abs() < 1e-9);
    }

    #[test]
    fn a_lens_space_has_p_elements_and_none_but_the_identity_fixes_a_point() {
        use fk_geometry_spherical::S3;
        let lens = Quotient::<S3>::lens(7, 2);
        let elements = lens.translates(7);
        assert_eq!(elements.len(), 7, "the cyclic group of order seven");
        // Free: every element but the identity moves every point (it screws along the axis
        // and turns about it, both by a seventh or more).
        let probes = [
            S3::origin(),
            S3::exp(&S3::origin(), &(S3::origin_frame(0) * 1.0)),
            S3::exp(
                &S3::origin(),
                &(S3::origin_frame(1) * std::f64::consts::FRAC_PI_2),
            ),
        ];
        for element in &elements[1..] {
            for p in &probes {
                assert!(S3::distance(&S3::apply(&element.isometry, p), p) > 1e-3);
            }
        }
        // Its domain about the origin has the two faces of the generator and its inverse.
        assert_eq!(lens.faces().count(), 2);
    }
}
