[package]
name = "fk-geometry-euclidean"
description = "Euclidean plane and space (E², E³) as Fucklide geometries"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
fk-math.workspace = true
fk-geometry.workspace = true

[dev-dependencies]
fk-geometry = { workspace = true, features = ["battery"] }

[lints]
workspace = true
